### ISSUE TITLE
Look at Unity Learn tutorials

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame6#135]
Open UnityHub and go to "Learn" tab. Choose a microgame and complete the tutorial. Upload a screenshot when done.

**Comment by Maxduke1** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/98621353/152475659-98582e4a-caa6-40e0-a073-606b46b3969c.png)

**Comment by alyg563** [comment]
Looks great! Hope you learned something!

**Comment by alyg563** [comment]
@jyu359 Could you upload a screenshot of the work you did in the tutorial? Thanks!

**Comment by jyu359** [comment]
Hey @alyg563 Sorry I forgot. Here it is.
![completed game level](https://user-images.githubusercontent.com/98621183/153993379-bac724f5-20d7-4e70-ae9e-9601a158d543.JPG)

**Comment by alyg563** [comment]
Great job everyone!

**Comment by SillyTheKid** [comment]
![Screenshot 2022-03-08 142751](https://user-images.githubusercontent.com/90936785/157336537-e23174fd-effd-4004-92d9-0255bd922366.png)
