### ISSUE TITLE
Draw out enemy routes for Sewer Level

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame6#197]
**DUE: 2/13**
Upload your patrols here!

**Comment by schevenin** [comment]
![Purple Top-right Enemy](https://i.imgur.com/cyHcIBK.jpeg)

**Comment by MattWant** [comment]
![PatrolRoutes](https://user-images.githubusercontent.com/71905800/153794847-7afa2220-6b65-4b6b-aa6a-1e47259e8146.png)

**Comment by MattWant** [comment]
![PatrolRoutes](https://user-images.githubusercontent.com/71905800/153918571-b412dd8f-977d-4197-b765-ec59268d96d2.png)
Please let me know if this is good or if you want me to change it up a little

**Comment by MattWant** [comment]
![BottomRightPath1](https://user-images.githubusercontent.com/71905800/154110184-6499036d-e45c-49a5-bd85-a78359a088d1.png)
![BottomRightPath2](https://user-images.githubusercontent.com/71905800/154110197-23f55fcc-191c-4fe8-af22-b8877ac98bdb.png)
Here are two ideas for a bottom right path I tried to make a bit longer so this patrol isn't hitting any of the other patrols or making it harder on the player. Let me know what you think though.

**Comment by sawyer816** [comment]
<img width="786" alt="Screen Shot 2022-02-22 at 9 40 21 AM" src="https://user-images.githubusercontent.com/11799376/155189039-46394f3c-a11d-42dc-83da-2715a82a4f3d.png">
