### ISSUE TITLE
Finish Sewer Level Concept Art

### ISSUE THREAD

**Issue by ElizabethNewgard** [AztecGameLab/LongTermGame6#200]
Finish Sewer concept art, make a few scenes of the rats running, building components etc etc. 
Entrance Area
Crawl
and general tunnel 
Think about what materials are in a sewer, mud, shit, water, etc etc. 
Also think about rats and their glowing eyes and how that would look in the tunnel, ie how much light might be available in the tunnel, value schemes etc etc.

**Comment by NaseemTahbaz** [comment]
uploaded a concept to the git
