### ISSUE TITLE
Map out enemy routes

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame6#57]
Once I have merged my branch into the master, **please locate the enemies with your names and create a path for them on paper**.
The paths should be fairly short and be located where they have already been placed.
(When you implement into Unity) Please also view the #ltg-level-design channel for the guidance that Daniel gave me for this.
If you need any help conceptually or even with the pathing itself, please let me know.

**Upload a pic of your plan here when you're done.**

Planning:
**DUE 1/27** so it is ready to show on 1/28 during the meeting.
Implementation in Unity:
**DUE 2/1** so we can test before the 2/4 meeting.

**Comment by MattWant** [comment]
![MattsPaths](https://user-images.githubusercontent.com/71905800/151246448-b9b3b444-5e27-4923-bdf8-f867ba141eff.jpg)

**Comment by alyg563** [comment]
![unknown](https://user-images.githubusercontent.com/43483413/151273218-85bb016a-de6d-4537-a1a6-77187c6c3085.png)
@dominic-griffith

**Comment by MattWant** [comment]
![image](https://user-images.githubusercontent.com/71905800/152279050-bd934cc7-ca50-4ebe-b700-5f57006801f5.png)
