### ISSUE TITLE
Map out Sewer Level general layout

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame6#70]
3 different lock and key areas
DUE: 2/5

**Comment by Mattarr** [comment]
Initial Map Design document (changed map to be added)
[Sewer_Design_Document.pdf](https://github.com/AztecGameLab/LongTermGame6/files/8006670/Sewer_Design_Document.pdf)

**Comment by Mattarr** [comment]
UPDATED: Map Layout
![map layout updated](https://user-images.githubusercontent.com/92897307/152651585-41892778-ac80-4c39-81d8-b3da0308a287.png)
Changes to original map layout depicted here with ***green stars***
![map layout updated highlights](https://user-images.githubusercontent.com/92897307/152651590-4dcff247-632d-455a-a11f-1af0f940d478.png)

**Comment by alyg563** [comment]
Perfect!

**Comment by sawyer816** [comment]
[Top Left Enemy Sewers](https://imgur.com/YF7n1BU)

**Comment by Mattarr** [comment]
> [Top Left Enemy Sewers](https://imgur.com/YF7n1BU)

That is actually the old sewer layout, if you could draw your AI pathing on this image instead, that would reflect the current map layout. Thanks!
![map layout updated](https://user-images.githubusercontent.com/92897307/153782223-08a6858d-fca4-435f-9bc4-615fab7e076b.png)
